[package]
name = "lox"
version = "0.1.0"
edition = "2021"
default-run = "lox"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lox-bytecode = { path = "../lox-bytecode" }
